project:
  type: website
  output-dir: docs
  

website:
  favicon: image_prob.png
  title: "Joseph Silveira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
        
      - href: resume.qmd
        text: resume
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



