project:
  type: website
  output-dir: docs
  

website:
  title: "Joseph Silveira"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



